const LOGIN_KEY='meuSalaoLogado',CLIENTES_KEY='meuSalaoClientes',USER_KEY='meuSalaoUsuario',PASS_KEY='meuSalaoSenha';
const clientes=()=>JSON.parse(localStorage.getItem(CLIENTES_KEY)||'[]');
const salvarClientes=l=>localStorage.setItem(CLIENTES_KEY,JSON.stringify(l));
function credenciais(){return{user:localStorage.getItem(USER_KEY)||'admin',pass:localStorage.getItem(PASS_KEY)||'meu salão 2025'}}
function diasAteAniversario(data){const h=new Date();h.setHours(0,0,0,0);const d=new Date(data+'T00:00:00');let p=new Date(h.getFullYear(),d.getMonth(),d.getDate());if(p<h)p.setFullYear(h.getFullYear()+1);return Math.round((p-h)/86400000)}
function proteger(){if(document.body.dataset.protected==='true'&&localStorage.getItem(LOGIN_KEY)!=='sim')location.href='login.html'}
function logout(){localStorage.removeItem(LOGIN_KEY);location.href='login.html'}
function iniciarLogin(){const f=document.getElementById('loginForm');if(!f)return;f.addEventListener('submit',e=>{e.preventDefault();const c=credenciais();if(usuario.value===c.user&&senha.value===c.pass){localStorage.setItem(LOGIN_KEY,'sim');location.href='dashboard.html'}else loginMsg.textContent='Usuário ou senha incorretos.'})}
function iniciarDashboard(){if(!document.getElementById('totalClientes'))return;const l=clientes();totalClientes.textContent=l.length;aniversariosProximos.textContent=l.filter(c=>diasAteAniversario(c.aniversario)<=30).length}
function iniciarClientes(){const f=document.getElementById('clienteForm');if(!f)return;f.addEventListener('submit',e=>{e.preventDefault();const l=clientes();l.push({id:Date.now(),nome:nome.value.trim(),telefone:telefone.value.replace(/\D/g,''),aniversario:aniversario.value});salvarClientes(l);f.reset();renderClientes()});renderClientes()}
function excluirCliente(id){if(confirm('Deseja excluir este cliente?')){salvarClientes(clientes().filter(c=>c.id!==id));renderClientes()}}
function whatsapp(c){const t=encodeURIComponent(`Olá, ${c.nome}! 💜 Passando para desejar um aniversário maravilhoso! Que seu novo ciclo seja cheio de beleza e momentos especiais. Com carinho, Meu Salão 2025 ✨`);window.open(`https://wa.me/${c.telefone}?text=${t}`,'_blank')}
function renderClientes(){const a=document.getElementById('listaClientes');if(!a)return;const l=clientes();if(!l.length){a.innerHTML='<div class="empty">✨ Nenhum cliente cadastrado ainda.<br>Comece adicionando seu primeiro cliente.</div>';return}a.innerHTML=l.map(c=>{const d=diasAteAniversario(c.aniversario),av=d===0?'🎉 É hoje!':d<=30?`🎂 Faltam ${d} dias`:`Em ${d} dias`,ini=c.nome.charAt(0).toUpperCase();return `<div class="client"><div class="person"><div class="avatar">${ini}</div><div><strong>${c.nome}</strong><br><span class="muted">${c.telefone}</span></div></div><div><span class="badge">${av}</span></div><div class="muted">${new Date(c.aniversario+'T00:00:00').toLocaleDateString('pt-BR',{day:'2-digit',month:'long'})}</div><div class="actions"><button class="btn ghost" onclick='whatsapp(${JSON.stringify(c)})'>WhatsApp</button><button class="btn danger" onclick="excluirCliente(${c.id})">Excluir</button></div></div>`}).join('')}
proteger();iniciarLogin();iniciarDashboard();iniciarClientes();